### ISSUE TITLE
[BUG?] Can't render the other yaml file

### ISSUE THREAD

**Issue by benyaminl** [vajahath/open-swagger-ui#22]
It shown error like this. 

![image](https://user-images.githubusercontent.com/2817332/198315457-973da662-a8ac-4d38-b99a-05d00f4be95c.png)
Is there anyway to set basePath via cli? Thank you

**Comment by vajahath** [comment]
Please share more details. What command you tried to run? Where is your file located?

**Comment by benyaminl** [comment]
@vajahath 
same as on docs, `open-swagger-ui ./swagger.json --open`, but I have sub folder on that folder 
```bash 
[ben@TP-X220 api]$ pwd
/home/ben/Code/AcerAPI/api
[ben@TP-X220 api]$ tree
.
├── schemas
│   ├── common
# ...... output ommited for privacy reason.....
│   │   ├── ListMetadataResult.yaml
# ...... output ommited for privacy reason.....
│   ├── MarketPlace.yaml
│   ├── Notification.yaml
# ...... output ommited for privacy reason.....
└── swagger.yaml

2 directories, 81 files
```

It can't render the file scheme folder, only the swagger. based on the error, there should be basePath, and I already run the command on the basePath, probably It need for cli command to add basePath. 


I think because the code https://github.com/vajahath/open-swagger-ui/blob/master/src/app.ts#L27 doesn't specify the basePath. https://github.com/scottie1984/swagger-ui-express/issues/189#issuecomment-738986346 

I just guessing for now, as I haven't test it yet, because your Url is = '/swagger-doc', and based on the code, seems you only render the swagger.yaml. https://github.com/vajahath/open-swagger-ui/blob/master/src/app.ts#L24

**Comment by vajahath** [comment]
Could you please provide a sample swagger file with the issue you mentioned (after removing any sensitive data)?

---

Just FYI: This tool was never meant to be a bundler. If you have multiple fragments of swagger doc and you reference those files in a main swagger.yaml file, then open-swagger-ui may not be able to render it. It expects everything bundled in a single file. You can bundle all your fragments into a single file using the [swagger-cli](https://www.npmjs.com/package/swagger-cli).

So you may add a bundling step to your workflow using the swagger-cli. Once the bundling is completed, open the output swagger file in open-swagger-ui.
Also, if you wanted to use basePath, you could add it directly to the swagger file: like https://github.com/vajahath/open-swagger-ui/blob/master/tests/swagger.yaml#L13.

**Comment by benyaminl** [comment]
@vajahath I think it's clear enough, I will use swagger UI docker image. Thanks for clarifying.
